# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:

  - stage: Build
    displayName: Build and Zip
    jobs:
    - job: zipProjectFiles
      displayName: Build Express Server
      pool:
        vmImage: 'ubuntu-latest'
      steps:

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
      
              echo 'Hello world'
      
              ls

        - task: NodeTool@0
          inputs:
            versionSpec: 10.16.0
          displayName: Install Node & Yarn
        - script: |
            cd BuildApp
            npm install
            yarn install

        - task: ArchiveFiles@2
          displayName: Zip App
          inputs:
            rootFolderOrFile: 'BuildApp'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/server.zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: Publish Artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'server-drop'
            publishLocation: 'Container'
            
  - stage: Deploy
    displayName: Deploy to Raspberry Pi Zero
    dependsOn: Build
    jobs:
    - deployment: deployToPiZero
      displayName: Deploy to Raspberry Pi Zero
      pool:
        vmImage: 'ubuntu-latest'
      environment: Development
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                displayName: Download Drop
                inputs:
                  buildType: 'current'
                  artifactName: 'server-drop'
                  downloadPath: '$(System.ArtifactsDirectory)/server-drop'

              - task: Bash@3
                displayName: Unzip
                inputs:
                  targetType: 'inline'
                  script: |
                    # Write your commands here
      
                    echo $(System.ArtifactsDirectory)
                    
                    echo "unzip server.zip"
                    
                    unzip $(System.ArtifactsDirectory)/server-drop/server.zip -d server
              
              - task: DownloadSecureFile@1
                name: envFile
                displayName: Download Env File
                inputs:
                  secureFile: '.env'

              - task: Bash@3
                displayName: Add Env File & Re-Zip
                inputs:
                  targetType: 'inline'
                  script: |
                    echo "changing directory"
                    
                    cd server
                    
                    echo "copying .env to server directory"
                    
                    cp $(envFile.secureFilePath)/.env $(System.ArtifactsDirectory)/server-drop/server
                    
                    echo "navigation back to server directory"
                    
                    cd ..
                    
                    echo "zipping server"
                    
                    zip -r server.zip server

              - task: CopyFilesOverSSH@0
                displayName: 'Copy Files to SSH'
                inputs:
                  sshEndpoint: 'raspberrypizero'
                  sourceFolder: '$(System.ArtifactsDirectory)/server-drop'
                  contents: '**'
                  targetFolder: 'Documents'
                  readyTimeout: '20000'
