# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:

  - stage: Zip
    displayName: Zip Files
    jobs:
    - job: zipProjectFiles
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: CopyFiles@2
          displayName: 'Copy Zip to Artifacts'
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '**/*.zip'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            flattenFolders: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'server-drop'
            publishLocation: 'Container'


