# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:

  - stage: Zip
    displayName: Zip Files
    jobs:
    - job: zipProjectFiles
      pool:
        vmImage: 'ubuntu-latest'
      steps:

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
      
              echo 'Hello world'
      
              ls

        - task: NodeTool@0 
          inputs:
            versionSpec: 10.16.0
          displayName: install node and yarn
        - script: |
            cd BuildApp
            npm install
            yarn install

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: 'BuildApp'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/server.zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'server-drop'
            publishLocation: 'Container'
            
  - stage: Deploy
    displayName: Deploy to Raspberry Pi Zero
    dependsOn: Zip
    jobs:
    - deployment: deployToPiZero
      displayName: Deploy to Raspberry Pi Zero
      pool:
        vmImage: 'ubuntu-latest'
      environment: Development
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'server-drop'
                  downloadPath: '$(System.ArtifactsDirectory)/server-drop'

              - task: Bash@3
                displayName: unzip & add .env file & rezip
                inputs:
                  targetType: 'inline'
                  script: |
                    # Write your commands here
      
                    echo $(System.ArtifactsDirectory)
                    ls
                    unzip $(System.ArtifactsDirectory)/server-drop/server.zip -d server
                    cd server
                    cat > .env
                    echo "LS_TOKEN=wu63wfmqjhrnsl3lic4p6c6tg3f5cgwsmxi4cbrw6y5vl6rersvq" >> .env
                    echo "LS_URL=https://dev.azure.com/lonelysasquatch/roasted/_apis/build/builds?$top=1&api-version=5.1" >> .env
                    echo "PORT=3001" >> .env
                    zip -r server.zip server

              - task: CopyFilesOverSSH@0
                displayName: 'Copy Files to SSH'
                inputs:
                  sshEndpoint: 'raspberrypizero'
                  sourceFolder: '$(System.ArtifactsDirectory)/server-drop'
                  contents: '**'
                  targetFolder: 'Documents'
                  readyTimeout: '20000'
